### ISSUE TITLE
Question : Why to put API inside Identity Server?

### ISSUE THREAD

**Issue by AlexandraDamaschin** [IdentityServer/IdentityServer4.Demo#3]
https://github.com/IdentityServer/IdentityServer4.Demo/blob/ac2d5ab105bf0c21e0762a36d8629c9a5545afab/src/IdentityServer4Demo/Api/TestController.cs#L8

Why do you consider that is a good idea to put the API inside the Identity Server? 
It will not be better to have a separate project for the API?

**Comment by leastprivilege** [comment]
Agreed. It's a demo.
